// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get a summary of John Ryan Halligan: background, current roles, and contact info.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "Name: John Ryan Halligan",
          "Education: Georgia Institute of Technology \u2014 Scheller College of Business, BSBA concentrating in Information Technology Management. Minors: Computing & Business (Denning T&M Program), Business of Sport & Entertainment.",
          "Current roles: Player Personnel Intern, Georgia Tech Football (Jan 2026 - Present).",
          "Previous: Scouting & Analytics Intern, Reel Analytics (Jan 2025 - Dec 2025).",
          "Focus: analytics, technology, and operations \u2014 especially in sports.",
          "Contact: rhalligan@gmail.com",
          "Website: https://halligan-ventures.lovable.app"
        ].join("\n")
      }
    ]
  })
});

// src/lib/mcp/tools/get-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_experience_default = defineTool2({
  name: "get_experience",
  title: "Get experience",
  description: "List John Ryan Halligan's professional experience with roles, organizations, and dates.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          [
            {
              role: "Player Personnel Intern",
              organization: "Georgia Tech Football",
              period: "January 2026 - Present",
              highlights: [
                "Streamline recruiting event logistics.",
                "Leverage specialized scouting systems to enhance data accuracy and workflow efficiency."
              ]
            },
            {
              role: "Scouting & Analytics Intern",
              organization: "Reel Analytics",
              period: "January 2025 - December 2025",
              highlights: [
                "Analyzed 250+ NFL Draft prospects using HUDL film, PFF grades, and position-specific metrics.",
                "Produced weekly advanced scouting reports for the University of Colorado."
              ]
            },
            {
              role: "Student Equipment Manager",
              organization: "Georgia Tech Football",
              period: "2023 - 2025"
            }
          ],
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/tools/get-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_projects_default = defineTool3({
  name: "get_projects",
  title: "Get projects",
  description: "List John Ryan Halligan's projects and collaborations with short descriptions and site links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const base = "https://halligan-ventures.lovable.app";
    const items = [
      { name: "Personal Projects", description: "Design & Analysis", url: `${base}/work/personal` },
      { name: "Georgia Tech Football", description: "Player Personnel Intern", url: `${base}/work/gt-football` },
      { name: "Reel Analytics", description: "Scouting & Analytics Intern (Jan 2025 - Dec 2025)", url: `${base}/work/reel-analytics` },
      { name: "GT Sports Business Club", description: "Atlanta Hawks Marketing Team Lead", url: `${base}/work/sbc` },
      { name: "Sigma Nu Fraternity", description: "Rush Chairman & Athletics Chairman", url: `${base}/work/sigma-nu` },
      { name: "Vertically Integrated Projects", description: "Sports Valuation & Analytics Team", url: `${base}/work/vip` }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { projects: items }
    };
  }
});

// src/lib/mcp/tools/get-education.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_education_default = defineTool4({
  name: "get_education",
  title: "Get education",
  description: "Get John Ryan Halligan's education details, minors, special programs, and honors.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "Georgia Institute of Technology \u2014 Scheller College of Business",
          "Degree: BSBA, concentration in Information Technology Management",
          "Minors: Computing & Business (Denning T&M Program), Business of Sport & Entertainment",
          "Special Programs: Denning Technology & Management Program",
          "Honors: Dow Chemical \u2013 P.C. McCutcheon Prize for Outstanding Achievement in Business",
          "High School: Dunwoody High School"
        ].join("\n")
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "halligan-ventures-mcp",
  title: "Halligan Ventures MCP",
  version: "0.1.0",
  instructions: "Portfolio tools for John Ryan Halligan. Use `get_profile` for a summary, `get_experience` for roles, `get_projects` for projects & collaborations, and `get_education` for education details.",
  tools: [get_profile_default, get_experience_default, get_projects_default, get_education_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
